apiVersion: v1
kind: Pod
metadata:
  labels:
    type: webui-type
spec:
  containers:
    - name: webui
      image: giovaz94/tea-store-general
      imagePullPolicy: Always
      ports:
        - containerPort: 8001
      resources:
        requests:
          cpu: "10m"
          memory: "10M"
      env:
        - name: MCL
          value: "150"
        - name: SERVICE_NAME
          value: "webUI"
        - name: PORT_IMAGE_SERVICE
          type: image-service-type
        - name: PORT_PERSISTENCE_SERVICE
          type: "persistence-service-type"
        - name: PORT_AUTH_SERVICE
          type: "auth-service-type"
        - name: PORT_RECOMMENDER_SERVICE
          type: "recommender-service-type"
        - name: PORT
          value: "8001"
        - name: OUTPUT_SERVICES
          value: '{"http://recommender-service:8005/request":"1","http://image-service:8004/request":"2","http://persistence-service:8003/request":"1","http://auth-service:8002/request":"1"}'
  restartPolicy: Always
