apiVersion: v1
kind: Service
type: attachment-manager-service-type
metadata:
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: "/metrics"
spec:
  selector:
    type: attachment-manager-type
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

ports:
  strong:
    - type: "attachment-manager-type"
      value: 1