apiVersion: v1
kind: Pod
type: recommender-type    
spec:
  containers:
    - name: recommender
      image: giovaz94/tea-store-general
      imagePullPolicy: Always
      ports:
        - containerPort: 8005
      resources:
        requests:
          cpu: "10m"
          memory: "10M"
      env:
        - name: MCL
          value: "190"
        - name: SERVICE_NAME
          value: "recommender"
        - name: PORT
          value: "8005"
  restartPolicy: Always
