apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample-test
spec:
  cleanup: 'post'
  parallelism: 4
  script:
    configMap:
      name: ltest
      file: main.js
  separate: false
  runner:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
    resources:
      limits:
        cpu: 200m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
  starter:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
      runAsNonRoot: true
