apiVersion: v1
kind: Pod
type: birex-alerting-type
spec:
  containers:
    - image: lukesmolo/public:birex-alerting_0.0.4
      name: birex-alerting
      env:
      - name: PROCESS_URL
        value: "http://birex-processor-1:3000"
      - name: INTERVAL
        value: "3000"
      ports:
        - containerPort: 3001
      resources:
        requests:
          cpu: "10m"
          memory: "10M"

ports:
  strong:
    - type: "birex-data-processor-service-type"
      id: PORT_BIREX_DATA_PROCESSOR_SERVICE
      value: 1

    - type: "birex-alerting-service-type"
      id: PORT_BIREX_ALERTING_SERVICE
      value: 1


  
