apiVersion: v1
kind: Pod
metadata:
  labels:
    type: persistence-type
spec:
  containers:
    - name: persistence
      image: giovaz94/tea-store-general
      imagePullPolicy: Always
      ports:
        - containerPort: 8003
      resources:
        requests:
          cpu: "10m"
          memory: "10M"
      env:
        - name: MCL
          value: "190"
        - name: SERVICE_NAME
          value: "persistence"
        - name: PORT
          value: "8003"
  restartPolicy: Always
